### ISSUE TITLE
Build and run on Linux

### ISSUE THREAD

**Issue by Eragonfr** [mrDIMAS/hrir_sphere_builder#1]
I'm on Archlinux, I want to try rg3d-sound using an HRIR sphere.  
But the build command(using g++) in the README seems to be not correct, the file doesn't exist.  
And if I run `g++ -o hrtf_builder hrtf_builder.cpp` I get errors from g++.  
I'm using g++ 9.3.0.

[The errors](https://haste.breizh.pm/osanasubux.php)

**Comment by mrDIMAS** [comment]
Never tried to build it on linux honestly, I compiled in VS2015 which has only experimental std::filesystem support, can be fixed by #ifdef'ing stuff.

By the way, the repo already contains all HRIR spheres in here - https://github.com/mrDIMAS/hrir_sphere_builder/tree/master/hrtf_base/IRCAM , just use any of *.bin files. I should mention that in readme to make it clear for everyone, right now it is confusing.

**Comment by Eragonfr** [comment]
I need to ask some questions about how exactly that work.

But… that questions is related to rg3d-sound and hrtf sphere and the best "3d audio"
Can I use this issue to ask my questions or, can I use other platform to ask it ?

**Comment by mrDIMAS** [comment]
Yes, you can open issue, there is no problem with that.

**Comment by andreiltd** [comment]
Should be fixed by https://github.com/mrDIMAS/hrir_sphere_builder/pull/2,  see README
